name: Frontend Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Install Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: 14

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Install ESLint
#         run: npm install eslint

#       - name: Run ESLint
#         run: npm run lint

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run start

      - name: Upload build result
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./public/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Transfer build files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          password: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/deploy"
          strip_components: 1
